name: Trigger auto deployment for demoapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demoapps-AutoDeployTrigger-6ac94add-1349-4ec0-a890-41cc2bee94d4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DEMOAPPS_REGISTRY_USERNAME }}
          password: ${{ secrets.DEMOAPPS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jkudo/helloworld:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOAPPS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n demoapps -g demoapps --server docker.io --username  ${{ secrets.DEMOAPPS_REGISTRY_USERNAME }} --password ${{ secrets.DEMOAPPS_REGISTRY_PASSWORD }}
            az containerapp update -n demoapps -g demoapps --image jkudo/helloworld:${{ github.sha }}
